### ISSUE TITLE
Create PR's from sublime?

### ISSUE THREAD

**Issue by joneshf** [wbond/ChannelRepositoryTools#2]
Do you think it's worthwhile to add a command that creates a PR from sublime? I think it would have to do something with github auth and what not. So maybe it's more effort than it's worth, but it seems like a pretty decent idea.

**Comment by FichteFoll** [comment]
For the record, I do believe that a package (or CLI tool) that assists or drives the process of adding a package to the default channel is a good idea. However, this should be done by skipping the Github and PR procedure (including a review) entirely, because it is cumbersome, a thankless job and nobody wants to do it.
